In [44]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import os 

In [2]:
pwd

'C:\\Users\\XNovaQ.23\\Documents\\Git JN\\Sivabalan_Xnovaq\\Ai model class adn example\\Day 2'

In [4]:
os.chdir ('C:\\Users\\XNovaQ.23\\Documents\\Git JN\\Sivabalan_Xnovaq\\Ai model class adn example\\Day 2')

In [5]:
pwd

'C:\\Users\\XNovaQ.23\\Documents\\Git JN\\Sivabalan_Xnovaq\\Ai model class adn example\\Day 2'

In [6]:
df1= pd.read_excel ('Data Preprocessing Data File.xlsx')
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [41]:

def highlight_null(val):
    color = 'teal' if pd.isnull(val) else ''
    return 'background-color: %s' % color
    


In [42]:
color_null = df1.style.map(highlight_null)

display (color_null)


In [23]:
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [10]:
x = df1.iloc[:,0:3]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [11]:
x = df1.iloc[:,:-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [12]:
y = df1.iloc[:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [13]:
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [14]:
x[:,1]

array([44.0, 27.0, nan, 39.0, nan, 35.0, 39.0, 48.0, 50.0, 37.0],
      dtype=object)

In [15]:
x[:,1:2]

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [45]:
from sklearn.impute import SimpleImputer
si =SimpleImputer()

si.fit_transform(x[:,1:2])

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [43]:
'''
strategy : str or Callable, default='mean'
    The imputation strategy.

    - If "mean", then replace missing values using the mean along
      each column. Can only be used with numeric data.
    - If "median", then replace missing values using the median along
      each column. Can only be used with numeric data.
    - If "most_frequent", then replace missing using the most frequent
      value along each column. Can be used with strings or numeric data.
      If there is more than one such value, only the smallest is returned.
    - If "constant", then replace missing values with fill_value. Can be
      used with strings or numeric data.

'''
from sklearn.impute import SimpleImputer
si =SimpleImputer(strategy= 'median')
si.fit_transform(x[:,1:2])

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [41]:
from sklearn.impute import SimpleImputer
si =SimpleImputer(strategy= 'constant',fill_value =555)
si.fit_transform(x[:,1:2])

array([[44.0],
       [27.0],
       [555],
       [39.0],
       [555],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [18]:
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [19]:
from sklearn.impute import SimpleImputer
si =SimpleImputer(strategy= 'most_frequent')
si.fit_transform(x[:,0:1])

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [20]:
from sklearn.impute import SimpleImputer
si =SimpleImputer(strategy= 'most_frequent')
x[:,0:1]= si.fit_transform(x[:,0:1])
print (pd.DataFrame (x))

          0     1        2
0   France   44.0  72000.0
1   France   27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0


In [21]:
from sklearn.impute import SimpleImputer
si =SimpleImputer(strategy= 'mean')
x[:,1:2]= si.fit_transform(x[:,1:2])
print (pd.DataFrame (x))

          0       1        2
0   France     44.0  72000.0
1   France     27.0  48000.0
2  Germany   39.875  54000.0
3    Spain     39.0      NaN
4  Germany   39.875  64000.0
5   France     35.0  58000.0
6    Spain     39.0  52000.0
7   France     48.0      NaN
8  Germany     50.0  83000.0
9   France     37.0  67000.0


In [22]:
from sklearn.impute import SimpleImputer
si =SimpleImputer(strategy= 'mean')
x[:,2:]= si.fit_transform(x[:,2:])
print (pd.DataFrame (x))

          0       1        2
0   France     44.0  72000.0
1   France     27.0  48000.0
2  Germany   39.875  54000.0
3    Spain     39.0  62250.0
4  Germany   39.875  64000.0
5   France     35.0  58000.0
6    Spain     39.0  52000.0
7   France     48.0  62250.0
8  Germany     50.0  83000.0
9   France     37.0  67000.0


In [23]:
x[:,0:1]

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [24]:
x[:,0]

array(['France ', 'France ', 'Germany ', 'Spain ', 'Germany ', 'France ',
       'Spain ', 'France ', 'Germany ', 'France '], dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0]= le.fit_transform (x[:,0])
print (x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 39.875 54000.0]
 [2 39.0 62250.0]
 [1 39.875 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [56]:
x

array([[0, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0]= le.fit_transform (x[:,0])
print (x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 39.875 54000.0]
 [2 39.0 62250.0]
 [1 39.875 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [27]:
'''
transformers : list of tuples
    List of (name, transformer, columns) tuples specifying the
    transformer objects to be applied to subsets of the data.
'''
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =ColumnTransformer([('onehot',OneHotEncoder(),[0] )])
ct.fit_transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [28]:
'''
remainder : {'drop', 'passthrough'} 
'''
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =ColumnTransformer([('onehot',OneHotEncoder(),[0] )], remainder = 'passthrough')
x = ct.fit_transform(x)
pd.DataFrame (x)

0    1    2       3        4
0  1.0  0.0  0.0    44.0  72000.0
1  1.0  0.0  0.0    27.0  48000.0
2  0.0  1.0  0.0  39.875  54000.0
3  0.0  0.0  1.0    39.0  62250.0
4  0.0  1.0  0.0  39.875  64000.0
5  1.0  0.0  0.0    35.0  58000.0
6  0.0  0.0  1.0    39.0  52000.0
7  1.0  0.0  0.0    48.0  62250.0
8  0.0  1.0  0.0    50.0  83000.0
9  1.0  0.0  0.0    37.0  67000.0

In [29]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [30]:
le_y = LabelEncoder()
y= le_y.fit_transform (y)
print (y)

[0 1 0 0 1 1 0 1 0 1]


In [31]:
pd.DataFrame(x)

0    1    2       3        4
0  1.0  0.0  0.0    44.0  72000.0
1  1.0  0.0  0.0    27.0  48000.0
2  0.0  1.0  0.0  39.875  54000.0
3  0.0  0.0  1.0    39.0  62250.0
4  0.0  1.0  0.0  39.875  64000.0
5  1.0  0.0  0.0    35.0  58000.0
6  0.0  0.0  1.0    39.0  52000.0
7  1.0  0.0  0.0    48.0  62250.0
8  0.0  1.0  0.0    50.0  83000.0
9  1.0  0.0  0.0    37.0  67000.0

In [32]:
from sklearn.preprocessing import StandardScaler
std_sca= StandardScaler()
x_STD = std_sca.fit_transform(x)
print (pd.DataFrame(x_STD))


     0         1    2         3         4
0  1.0 -0.654654 -0.5  0.664912  1.002707
1  1.0 -0.654654 -0.5 -2.075331 -1.465494
2 -1.0  1.527525 -0.5  0.000000 -0.848444
3 -1.0 -0.654654  2.0 -0.141042  0.000000
4 -1.0  1.527525 -0.5  0.000000  0.179973
5  1.0 -0.654654 -0.5 -0.785805 -0.437077
6 -1.0 -0.654654  2.0 -0.141042 -1.054127
7  1.0 -0.654654 -0.5  1.309675  0.000000
8 -1.0  1.527525 -0.5  1.632056  2.133965
9  1.0 -0.654654 -0.5 -0.463423  0.488498


In [33]:

from sklearn.preprocessing import MinMaxScaler
Nm_x= MinMaxScaler()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))



     0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  1.0  0.0  0.0  0.000000  0.000000
2  0.0  1.0  0.0  0.559783  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.559783  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857


In [72]:
pd.DataFrame (x)

0    1    2       3        4
0  1.0  0.0  0.0    44.0  72000.0
1  1.0  0.0  0.0    27.0  48000.0
2  0.0  1.0  0.0  39.875  54000.0
3  0.0  0.0  1.0    39.0  62250.0
4  0.0  1.0  0.0  39.875  64000.0
5  1.0  0.0  0.0    35.0  58000.0
6  0.0  0.0  1.0    39.0  52000.0
7  1.0  0.0  0.0    48.0  62250.0
8  0.0  1.0  0.0    50.0  83000.0
9  1.0  0.0  0.0    37.0  67000.0

In [35]:
from sklearn.preprocessing import Normalizer
Nm_x= Normalizer()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))


          0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000000  0.000019  0.000000  0.000738  1.0
3  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000000  0.000016  0.000000  0.000623  1.0
5  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000015  0.000000  0.000000  0.000552  1.0
