In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os 
import tensorflow as tf


In [2]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 20\\')

In [3]:
df = pd.read_csv('kc_house_data.csv')
display (df)


id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [4]:
df = df.drop('id',axis=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           21613 non-null  object 
 1   price          21613 non-null  float64
 2   bedrooms       21613 non-null  int64  
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64  
 5   sqft_lot       21613 non-null  int64  
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64  
 8   view           21613 non-null  int64  
 9   condition      21613 non-null  int64  
 10  grade          21613 non-null  int64  
 11  sqft_above     21613 non-null  int64  
 12  sqft_basement  21613 non-null  int64  
 13  yr_built       21613 non-null  int64  
 14  yr_renovated   21613 non-null  int64  
 15  zipcode        21613 non-null  int64  
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 18  sqft_l

In [6]:
df['date'] = pd.to_datetime(df['date'])



In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   date           21613 non-null  datetime64[ns]
 1   price          21613 non-null  float64       
 2   bedrooms       21613 non-null  int64         
 3   bathrooms      21613 non-null  float64       
 4   sqft_living    21613 non-null  int64         
 5   sqft_lot       21613 non-null  int64         
 6   floors         21613 non-null  float64       
 7   waterfront     21613 non-null  int64         
 8   view           21613 non-null  int64         
 9   condition      21613 non-null  int64         
 10  grade          21613 non-null  int64         
 11  sqft_above     21613 non-null  int64         
 12  sqft_basement  21613 non-null  int64         
 13  yr_built       21613 non-null  int64         
 14  yr_renovated   21613 non-null  int64         
 15  zipcode        2161

In [8]:
df['month'] = df['date'].apply(lambda date:date.month)
df['year'] = df['date'].apply(lambda date:date.year)
display (df)

date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0     2014-10-13  221900.0         3       1.00         1180      5650   
1     2014-12-09  538000.0         3       2.25         2570      7242   
2     2015-02-25  180000.0         2       1.00          770     10000   
3     2014-12-09  604000.0         4       3.00         1960      5000   
4     2015-02-18  510000.0         3       2.00         1680      8080   
...          ...       ...       ...        ...          ...       ...   
21608 2014-05-21  360000.0         3       2.50         1530      1131   
21609 2015-02-23  400000.0         4       2.50         2310      5813   
21610 2014-06-23  402101.0         2       0.75         1020      1350   
21611 2015-01-16  400000.0         3       2.50         1600      2388   
21612 2014-10-15  325000.0         2       0.75         1020      1076   

       floors  waterfront  view  condition  ...  sqft_basement  yr_built  \
0         1.0           0     0          3  ...              0      1955   
1         2.0           0     0          3  ...            400      1951   
2         1.0           0     0          3  ...              0      1933   
3         1.0           0     0          5  ...            910      1965   
4         1.0           0     0          3  ...              0      1987   
...       ...         ...   ...        ...  ...            ...       ...   
21608     3.0           0     0          3  ...              0      2009   
21609     2.0           0     0          3  ...              0      2014   
21610     2.0           0     0          3  ...              0      2009   
21611     2.0           0     0          3  ...              0      2004   
21612     2.0           0     0          3  ...              0      2008   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0                 0    98178  47.5112 -122.257           1340        5650   
1              1991    98125  47.7210 -122.319           1690        7639   
2                 0    98028  47.7379 -122.233           2720        8062   
3                 0    98136  47.5208 -122.393           1360        5000   
4                 0    98074  47.6168 -122.045           1800        7503   
...             ...      ...      ...      ...            ...         ...   
21608             0    98103  47.6993 -122.346           1530        1509   
21609             0    98146  47.5107 -122.362           1830        7200   
21610             0    98144  47.5944 -122.299           1020        2007   
21611             0    98027  47.5345 -122.069           1410        1287   
21612             0    98144  47.5941 -122.299           1020        1357   

       month  year  
0         10  2014  
1         12  2014  
2          2  2015  
3         12  2014  
4          2  2015  
...      ...   ...  
21608      5  2014  
21609      2  2015  
21610      6  2014  
21611      1  2015  
21612     10  2014  

[21613 rows x 22 columns]

In [9]:
df = df.drop('date',axis=1).drop('zipcode',axis=1)
display (df)


price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0   
1      538000.0         3       2.25         2570      7242     2.0   
2      180000.0         2       1.00          770     10000     1.0   
3      604000.0         4       3.00         1960      5000     1.0   
4      510000.0         3       2.00         1680      8080     1.0   
...         ...       ...        ...          ...       ...     ...   
21608  360000.0         3       2.50         1530      1131     3.0   
21609  400000.0         4       2.50         2310      5813     2.0   
21610  402101.0         2       0.75         1020      1350     2.0   
21611  400000.0         3       2.50         1600      2388     2.0   
21612  325000.0         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21608           0     0          3      8        1530              0   
21609           0     0          3      8        2310              0   
21610           0     0          3      7        1020              0   
21611           0     0          3      8        1600              0   
21612           0     0          3      7        1020              0   

       yr_built  yr_renovated      lat     long  sqft_living15  sqft_lot15  \
0          1955             0  47.5112 -122.257           1340        5650   
1          1951          1991  47.7210 -122.319           1690        7639   
2          1933             0  47.7379 -122.233           2720        8062   
3          1965             0  47.5208 -122.393           1360        5000   
4          1987             0  47.6168 -122.045           1800        7503   
...         ...           ...      ...      ...            ...         ...   
21608      2009             0  47.6993 -122.346           1530        1509   
21609      2014             0  47.5107 -122.362           1830        7200   
21610      2009             0  47.5944 -122.299           1020        2007   
21611      2004             0  47.5345 -122.069           1410        1287   
21612      2008             0  47.5941 -122.299           1020        1357   

       month  year  
0         10  2014  
1         12  2014  
2          2  2015  
3         12  2014  
4          2  2015  
...      ...   ...  
21608      5  2014  
21609      2  2015  
21610      6  2014  
21611      1  2015  
21612     10  2014  

[21613 rows x 20 columns]

In [10]:
X = df.drop('price',axis=1)
y = df['price']


In [11]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)
print (X_train.shape)
print (X_test.shape)


(15129, 19)
(6484, 19)


In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train= scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [13]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam



In [14]:
model = Sequential()

model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(1))


In [15]:

model.compile(optimizer='adam',loss='mse',metrics = ['accuracy'] )


In [16]:

epochs = 501
for i in range (epochs): 
    if (i+1)%25 == 1:
        print (str (i+1),'/',str(epochs))
        model.fit(x=X_train,  y=y_train,validation_data=(X_test, y_test), verbose=1)
    else:
        model.fit(x=X_train,  y=y_train,validation_data=(X_test, y_test), verbose=0)
        


1 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0000e+00 - loss: 393517268992.0000 - val_accuracy: 0.0000e+00 - val_loss: 253716545536.0000
26 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 38562193408.0000 - val_accuracy: 0.0000e+00 - val_loss: 37972779008.0000
51 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 33937086464.0000 - val_accuracy: 0.0000e+00 - val_loss: 33404880896.0000
76 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 32172875776.0000 - val_accuracy: 0.0000e+00 - val_loss: 31513800704.0000
101 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 31086786560.0000 - val_accuracy: 0.0000e+00 - val_loss: 30481438720.0000
126 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 30261741568.0000 - val_accuracy: 0.0000e+00 - val_loss: 29695248384.0000
151 / 501
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00

In [17]:
predictions = model.predict(X_test)
print (predictions) 


203/203 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[5.7024844e+05]
 [6.2939356e+05]
 [6.5393125e+05]
 ...
 [3.7716944e+05]
 [2.2000219e+05]
 [1.0140436e+06]]


In [18]:
print (y_test)

3834      349950.0
1348      450000.0
20366     635000.0
16617     355500.0
20925     246950.0
           ...    
1398      465000.0
3364      418000.0
18958     394250.0
17845     249500.0
16335    1350000.0
Name: price, Length: 6484, dtype: float64


In [19]:

from sklearn.metrics import mean_squared_error,mean_absolute_error,explained_variance_score,r2_score
print ('Mean Absolute Error',mean_absolute_error(y_test,predictions))
print ('RMSE',np.sqrt(mean_squared_error(y_test,predictions)))
print ('Accuracy',r2_score(y_test,predictions))


Mean Absolute Error 102538.7712771341
RMSE 166762.85333223682
Accuracy 0.8017475051765922


In [20]:

predictions = model.predict(X_train)
from sklearn.metrics import mean_squared_error,mean_absolute_error,explained_variance_score,r2_score
print ('Mean Absolute Error',mean_absolute_error(y_train,predictions))
print ('RMSE',np.sqrt(mean_squared_error(y_train,predictions)))
print ('Accuracy',r2_score(y_train,predictions))   


473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step
Mean Absolute Error 100980.81068384807
RMSE 156999.70262390678
Accuracy 0.8138564851615651


In [21]:
single_house = df.drop('price',axis=1).iloc[0:1]
single_house = scaler.transform(single_house)
display (single_house)


array([[0.27272727, 0.125     , 0.06716981, 0.00310751, 0.        ,
        0.        , 0.        , 0.5       , 0.5       , 0.09758772,
        0.        , 0.47826087, 0.        , 0.57149751, 0.21760797,
        0.16193426, 0.00573322, 0.81818182, 0.        ]])

In [22]:
print (model.predict(single_house))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[[282070.75]]


In [23]:
print (df['price'].iloc[0:1])

0    221900.0
Name: price, dtype: float64


In [24]:
df.drop('price',axis=1).iloc[0:1]

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3        1.0         1180      5650     1.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   

       lat     long  sqft_living15  sqft_lot15  month  year  
0  47.5112 -122.257           1340        5650     10  2014

In [25]:
single_house = df.drop('price',axis=1).iloc[1:2]
single_house = scaler.transform(single_house)
display (single_house)

array([[0.27272727, 0.28125   , 0.17207547, 0.00407187, 0.4       ,
        0.        , 0.        , 0.5       , 0.5       , 0.20614035,
        0.0968523 , 0.44347826, 0.98808933, 0.90895931, 0.16611296,
        0.22216486, 0.008018  , 1.        , 0.        ]])

In [26]:
print (model.predict(single_house))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
[[630069.2]]


In [27]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)
print (X_train.shape)
print (X_test.shape)

(15129, 19)
(6484, 19)


In [28]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
print (lr)


LinearRegression()


In [29]:
y_pred= lr.predict(X_test)
print (y_pred)


[530480.0288465  665507.34422842 552306.52594796 ... 591365.32726008
 146416.71022829 980568.05686857]


In [38]:
df_y_test= pd.DataFrame(y_test.values, columns = ['Salary'])
df_y_test_pred =  pd.DataFrame(y_pred, columns = ['Prediction'])
y_test_pred = pd.concat ([df_y_test, df_y_test_pred ],axis =1)
y_test_pred['Difference'] =df_y_test ['Salary']- df_y_test_pred['Prediction']
print (y_test_pred)


         Salary     Prediction     Difference
0      349950.0  530480.028847 -180530.028847
1      450000.0  665507.344228 -215507.344228
2      635000.0  552306.525948   82693.474052
3      355500.0  346983.015582    8516.984418
4      246950.0   62664.854188  184285.145812
...         ...            ...            ...
6479   465000.0  523894.702373  -58894.702373
6480   418000.0  399551.811923   18448.188077
6481   394250.0  591365.327260 -197115.327260
6482   249500.0  146416.710228  103083.289772
6483  1350000.0  980568.056869  369431.943131

[6484 rows x 3 columns]


In [37]:
df_y_test= pd.DataFrame(y_test.values , columns = ['Salary'])
df_y_test

Salary
0      349950.0
1      450000.0
2      635000.0
3      355500.0
4      246950.0
...         ...
6479   465000.0
6480   418000.0
6481   394250.0
6482   249500.0
6483  1350000.0

[6484 rows x 1 columns]

In [36]:
y_test.values

array([ 349950.,  450000.,  635000., ...,  394250.,  249500., 1350000.],
      shape=(6484,))

In [39]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)
print (accuracy)


0.7048367008432201
