In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import os


In [2]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 13\\')

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset


User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [4]:
X = dataset.iloc[:, [2, 3]].values
print (X)


[[    42 121315]
 [    53  67214]
 [    59 111005]
 [    39  53414]
 [    39 114285]
 [    39 107458]
 [    20  85582]
 [    59 148335]
 [    48  80579]
 [    42 114204]
 [    32  87786]
 [    49 113544]
 [    55  88300]
 [    54 147066]
 [    57 139622]
 [    41 134716]
 [    51 116333]
 [    55  72567]
 [    44 123254]
 [    47 113548]
 [    52  79343]
 [    20 106149]
 [    40  59674]
 [    52  76333]
 [    28 118742]
 [    22 105897]
 [    25 114815]
 [    38  85428]
 [    57 114005]
 [    57 133402]
 [    43 106726]
 [    35  84550]
 [    34  96296]
 [    32  68964]
 [    55  90946]
 [    48  51787]
 [    22  53940]
 [    42 138928]
 [    59 116474]
 [    23  97284]
 [    40 132951]
 [    24 119308]
 [    50 120675]
 [    41 113547]
 [    52 102686]
 [    34 140262]
 [    20  54075]
 [    25  63715]
 [    46  56058]
 [    58  65052]
 [    38  72107]
 [    21 108656]
 [    42 120639]
 [    31  68033]
 [    26  80283]
 [    47  60952]
 [    31 123137]
 [    36  98529]
 [    25 12130

In [5]:
y = dataset.iloc[:, 4].values
print (y)


[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X


array([[ 0.17951354,  0.76103154],
       [ 1.11315372, -1.14804259],
       [ 1.622412  ,  0.39722026],
       [-0.0751156 , -1.63500628],
       [-0.0751156 ,  0.51296235],
       [-0.0751156 ,  0.27205647],
       [-1.68776681, -0.49988685],
       [ 1.622412  ,  1.71449234],
       [ 0.68877182, -0.67642883],
       [ 0.17951354,  0.51010409],
       [-0.66925025, -0.42211381],
       [ 0.7736482 ,  0.48681452],
       [ 1.28290648, -0.40397617],
       [ 1.1980301 ,  1.66971285],
       [ 1.45265924,  1.40703476],
       [ 0.09463716,  1.23391563],
       [ 0.94340096,  0.58523059],
       [ 1.28290648, -0.95915007],
       [ 0.3492663 ,  0.82945347],
       [ 0.60389544,  0.48695567],
       [ 1.02827734, -0.72004384],
       [-1.68776681,  0.2258655 ],
       [ 0.00976078, -1.41410826],
       [ 1.02827734, -0.82625839],
       [-1.00875577,  0.67023751],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.53166458],
       [-0.15999198, -0.50532108],
       [ 1.45265924,

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)


(300, 2)
(100, 2)
(300,)
(100,)


In [8]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'sigmoid', random_state = 0)
svm_classifier.fit(X_train, y_train) 


SVC(kernel='sigmoid', random_state=0)

In [9]:
svm_y_pred = svm_classifier.predict(X_test)
svm_y_pred


array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0])

In [10]:
from sklearn.metrics import confusion_matrix
svm_cm = confusion_matrix(y_test,svm_y_pred )
svm_cm


array([[40, 28],
       [19, 13]])

In [11]:
print (accuracy_score (y_test,svm_y_pred))

0.53


In [12]:

print(classification_report (y_test,svm_y_pred,zero_division=0))



              precision    recall  f1-score   support

           0       0.68      0.59      0.63        68
           1       0.32      0.41      0.36        32

    accuracy                           0.53       100
   macro avg       0.50      0.50      0.49       100
weighted avg       0.56      0.53      0.54       100



In [14]:
from sklearn.model_selection import cross_val_score
svm_accuracies = cross_val_score(estimator = svm_classifier, X = X_train, y = y_train, cv = 10)
print ('Mean', svm_accuracies.mean())
print ('STD',svm_accuracies.std())


Mean 0.5666666666666667
STD 0.06497862896539308


In [15]:
print (pd.DataFrame(svm_accuracies))

          0
0  0.533333
1  0.533333
2  0.533333
3  0.600000
4  0.666667
5  0.500000
6  0.500000
7  0.533333
8  0.566667
9  0.700000


In [16]:
from sklearn.model_selection import cross_val_score
svm_accuracies = cross_val_score(estimator = svm_classifier, X = X_train, y = y_train, cv = 5)
print ('Mean', svm_accuracies.mean())
print ('STD',svm_accuracies.std())


Mean 0.5700000000000001
STD 0.03399346342395189


In [17]:
print (pd.DataFrame(svm_accuracies))

          0
0  0.550000
1  0.583333
2  0.616667
3  0.516667
4  0.583333


In [18]:

from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)
log_y_pred = logmodel.predict(X_test)
print (log_y_pred)
print('\n Accuracy Score')
print (accuracy_score (y_test,log_y_pred))
print('\nClassification Report')
print(classification_report (y_test,log_y_pred,zero_division=0))
print('Confusion Matrix')
print (confusion_matrix (y_test,log_y_pred))


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 Accuracy Score
0.68

Classification Report
              precision    recall  f1-score   support

           0       0.68      1.00      0.81        68
           1       0.00      0.00      0.00        32

    accuracy                           0.68       100
   macro avg       0.34      0.50      0.40       100
weighted avg       0.46      0.68      0.55       100

Confusion Matrix
[[68  0]
 [32  0]]


In [19]:

from sklearn.model_selection import cross_val_score
log_accuracies = cross_val_score(estimator = logmodel, X = X_train, y = y_train, cv = 10)
print ('Mean', log_accuracies.mean())
print ('STD',log_accuracies.std())
print ('Individual Accuracies')
print (pd.DataFrame(log_accuracies))



Mean 0.6299999999999999
STD 0.01795054935711501
Individual Accuracies
          0
0  0.633333
1  0.633333
2  0.666667
3  0.633333
4  0.600000
5  0.633333
6  0.633333
7  0.633333
8  0.633333
9  0.600000


In [21]:

from sklearn.model_selection import LeaveOneOut
loout =LeaveOneOut()
loo_results = cross_val_score(logmodel,X = X_train, y = y_train, cv=10)
print ('Mean', loo_results.mean())
print ('STD',loo_results.std())
print ('Individual Accuracies')
print (pd.DataFrame(loo_results))


Mean 0.6299999999999999
STD 0.01795054935711501
Individual Accuracies
          0
0  0.633333
1  0.633333
2  0.666667
3  0.633333
4  0.600000
5  0.633333
6  0.633333
7  0.633333
8  0.633333
9  0.600000


In [20]:

from sklearn.model_selection import LeaveOneOut
loout =LeaveOneOut()
loo_results = cross_val_score(logmodel,X = X_train, y = y_train, cv=loout)
print ('Mean', loo_results.mean())
print ('STD',loo_results.std())
print ('Individual Accuracies')
print (pd.DataFrame(loo_results))


Mean 0.63
STD 0.48280430818293246
Individual Accuracies
       0
0    1.0
1    0.0
2    1.0
3    0.0
4    0.0
..   ...
295  0.0
296  1.0
297  1.0
298  1.0
299  1.0

[300 rows x 1 columns]
