In [1]:

import matplotlib.pyplot as plt
from keras import datasets
import numpy as np


In [2]:
(X_train, y_train), (X_test,y_test) = datasets.cifar10.load_data()
print (X_train.shape)
print (X_test.shape)


C:\ProgramData\anaconda3\envs\K_DL_Jan_2025\Lib\site-packages\keras\src\datasets\cifar.py:18: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  d = cPickle.load(f, encoding="bytes")


(50000, 32, 32, 3)
(10000, 32, 32, 3)


In [3]:
def plot_sample(X, y, index):
    plt.figure(figsize = (15,2))
    plt.imshow(X[index])
    plt.xlabel(classes[y[index]])


In [4]:
classes = ["airplane","automobile","bird","cat",
           "deer","dog","frog","horse","ship","truck"]
print (classes)


['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


In [5]:
y_train = y_train.reshape(-1,)
print (y_train)


[6 9 9 ... 9 1 1]


In [6]:
y_test = y_test.reshape(-1,)
print (y_test)


[3 8 8 ... 5 1 7]


In [7]:
X_train = X_train / 255.0
X_test = X_test / 255.0


In [8]:
print (X_train.shape)	

(50000, 32, 32, 3)


In [9]:
X_train= X_train.reshape (50000,3072)
print (X_train.shape)


(50000, 3072)


In [10]:
X_test= X_test.reshape (10000,3072)
print (X_test.shape)


(10000, 3072)


In [11]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(X_train,y_train)
print (GNB)


GaussianNB()


In [12]:
GNB_pred = GNB.predict(X_test)
print (GNB_pred)


[6 8 8 ... 6 5 4]


In [13]:

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print ('Accuracy')
print (accuracy_score (y_test, GNB_pred))
print ()
print ('Confusion Matrix')
cm = confusion_matrix (y_test , GNB_pred)
print (cm)
print ()
print ('Classification Report')
print(classification_report (y_test, GNB_pred, zero_division=0))



Accuracy
0.2976

Confusion Matrix
[[494  20  39  10  84  34  50   9 200  60]
 [141 166  24  31  66  72 192  19 121 168]
 [225  24  83  15 292  48 209  21  54  29]
 [163  36  54  76 151 129 262  26  34  69]
 [ 86   8  57  26 417  38 265  22  50  31]
 [156  17  55  51 167 264 159  36  57  38]
 [106   2  60  18 228  46 467  15  19  39]
 [134  24  36  41 228  94 102 131  72 138]
 [168  41  18  17  56  83  39   8 471  99]
 [144  67  17  20  48  32 101  23 141 407]]

Classification Report
              precision    recall  f1-score   support

           0       0.27      0.49      0.35      1000
           1       0.41      0.17      0.24      1000
           2       0.19      0.08      0.12      1000
           3       0.25      0.08      0.12      1000
           4       0.24      0.42      0.30      1000
           5       0.31      0.26      0.29      1000
           6       0.25      0.47      0.33      1000
           7       0.42      0.13      0.20      1000
           8       0.39  

In [16]:
from sklearn.linear_model import LogisticRegression
GNB = LogisticRegression()
GNB.fit(X_train,y_train)
print (GNB)


LogisticRegression()


C:\ProgramData\anaconda3\envs\K_DL_Jan_2025\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:

GNB_pred = GNB.predict(X_test)
print (GNB_pred)


[3 9 8 ... 5 5 7]


In [18]:

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print ('Accuracy')
print (accuracy_score (y_test, GNB_pred))
print ()
print ('Confusion Matrix')
cm = confusion_matrix (y_test , GNB_pred)
print (cm)
print ()
print ('Classification Report')
print(classification_report (y_test, GNB_pred, zero_division=0))



Accuracy
0.4063

Confusion Matrix
[[474  42  59  36  20  32  26  54 186  71]
 [ 57 492  21  30  22  42  37  52  80 167]
 [109  47 275  87 118  86 138  67  49  24]
 [ 39  59  97 252  55 206 124  48  47  73]
 [ 55  28 135  51 295  98 159 122  32  25]
 [ 41  45  91 144  81 369  86  70  40  33]
 [ 15  32  71 116 101  87 490  39  22  27]
 [ 46  44  73  54  92  84  49 438  41  79]
 [178  67  20  24   9  50   8  19 521 104]
 [ 80 190  21  20  17  30  41  48  96 457]]

Classification Report
              precision    recall  f1-score   support

           0       0.43      0.47      0.45      1000
           1       0.47      0.49      0.48      1000
           2       0.32      0.28      0.30      1000
           3       0.31      0.25      0.28      1000
           4       0.36      0.29      0.33      1000
           5       0.34      0.37      0.35      1000
           6       0.42      0.49      0.45      1000
           7       0.46      0.44      0.45      1000
           8       0.47  

In [20]:
from sklearn.tree import DecisionTreeClassifier
GNB =  DecisionTreeClassifier()
GNB.fit(X_train,y_train)
print (GNB)

DecisionTreeClassifier()


In [21]:
GNB_pred = GNB.predict(X_test)
print (GNB_pred)


[7 1 1 ... 2 5 4]


In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print ('Accuracy')
print (accuracy_score (y_test, GNB_pred))
print ()
print ('Confusion Matrix')
cm = confusion_matrix (y_test , GNB_pred)
print (cm)
print ()
print ('Classification Report')
print(classification_report (y_test, GNB_pred, zero_division=0))



Accuracy
0.2704

Confusion Matrix
[[360  75  85  55  60  57  33  48 156  71]
 [ 71 265  60  80  62  59  59  61 108 175]
 [ 95  50 228 100 140 114 108  83  37  45]
 [ 69  60 100 168 110 148 136  97  55  57]
 [ 57  50 163  89 234 106 133  91  33  44]
 [ 55  62 109 158  92 214 111  95  53  51]
 [ 40  53 143 126 130  88 282  67  25  46]
 [ 76  83  90  88  98 109  60 269  57  70]
 [144 110  51  50  41  42  30  43 388 101]
 [ 86 160  53  64  45  58  51  88  99 296]]

Classification Report
              precision    recall  f1-score   support

           0       0.34      0.36      0.35      1000
           1       0.27      0.27      0.27      1000
           2       0.21      0.23      0.22      1000
           3       0.17      0.17      0.17      1000
           4       0.23      0.23      0.23      1000
           5       0.22      0.21      0.21      1000
           6       0.28      0.28      0.28      1000
           7       0.29      0.27      0.28      1000
           8       0.38  