In [1]:

import numpy as np
import pandas as pd
import os


In [2]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 19\\')

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
display (dataset)


RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
X = dataset.iloc[:, 3:-1].values
print (X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
y = dataset.iloc[:, -1].values
print (y)


[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print (X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print (X)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
print (X.shape)

(10000, 12)


In [9]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_STD = sc.fit_transform(X)
display (pd.DataFrame(X_STD ))


0         1         2         3         4         5         6   \
0     0.997204 -0.578736 -0.573809 -0.326221 -1.095988  0.293517 -1.041760   
1    -1.002804 -0.578736  1.742740 -0.440036 -1.095988  0.198164 -1.387538   
2     0.997204 -0.578736 -0.573809 -1.536794 -1.095988  0.293517  1.032908   
3     0.997204 -0.578736 -0.573809  0.501521 -1.095988  0.007457 -1.387538   
4    -1.002804 -0.578736  1.742740  2.063884 -1.095988  0.388871 -1.041760   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.997204 -0.578736 -0.573809  1.246488  0.912419  0.007457 -0.004426   
9996  0.997204 -0.578736 -0.573809 -1.391939  0.912419 -0.373958  1.724464   
9997  0.997204 -0.578736 -0.573809  0.604988 -1.095988 -0.278604  0.687130   
9998 -1.002804  1.727904 -0.573809  1.256835  0.912419  0.293517 -0.695982   
9999  0.997204 -0.578736 -0.573809  1.463771 -1.095988 -1.041433 -0.350204   

            7         8         9         10        11  
0    -1.225848 -0.911583  0.646092  0.970243  0.021886  
1     0.117350 -0.911583 -1.547768  0.970243  0.216534  
2     1.333053  2.527057  0.646092 -1.030670  0.240687  
3    -1.225848  0.807737 -1.547768 -1.030670 -0.108918  
4     0.785728 -0.911583  0.646092  0.970243 -0.365276  
...        ...       ...       ...       ...       ...  
9995 -1.225848  0.807737  0.646092 -1.030670 -0.066419  
9996 -0.306379 -0.911583  0.646092  0.970243  0.027988  
9997 -1.225848 -0.911583 -1.547768  0.970243 -1.008643  
9998 -0.022608  0.807737  0.646092 -1.030670 -0.125231  
9999  0.859965 -0.911583  0.646092 -1.030670 -1.076370  

[10000 rows x 12 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_STD, y, test_size = 0.2, random_state = 0)
print (X_STD.shape)
print (X_train.shape)
print (X_test.shape)


(10000, 12)
(8000, 12)
(2000, 12)


In [11]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit (X_train,y_train)
print (dtc)


DecisionTreeClassifier()


In [12]:

y_pred = dtc.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print ("Accuracy")
print (accuracy_score(y_test, y_pred))
print ()
print ('Classification Report')
print (classification_report (y_test, y_pred))
print ()
cm = confusion_matrix(y_test, y_pred)
print(cm)


Accuracy
0.801

Classification Report
              precision    recall  f1-score   support

           0       0.89      0.86      0.87      1595
           1       0.51      0.58      0.54       405

    accuracy                           0.80      2000
   macro avg       0.70      0.72      0.71      2000
weighted avg       0.81      0.80      0.81      2000


[[1369  226]
 [ 172  233]]


In [13]:

yfull_pred = dtc.predict(X_STD)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print ("Accuracy")
print (accuracy_score(y,yfull_pred))
print ()
print ('Classification Report')
print (classification_report (y,yfull_pred))
print ()
cm = confusion_matrix(y,yfull_pred)
print(cm)



Accuracy
0.9602

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      7963
           1       0.89      0.92      0.90      2037

    accuracy                           0.96     10000
   macro avg       0.94      0.94      0.94     10000
weighted avg       0.96      0.96      0.96     10000


[[7737  226]
 [ 172 1865]]
