In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os


In [25]:
print ('Python Version')
!python --version
print ('Tensor Flow Version',tf.__version__)


Python Version
Python 3.13.11
Tensor Flow Version 2.20.0


In [26]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 19\\')

In [27]:
dataset = pd.read_csv('Churn_Modelling.csv')
display (dataset)


RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [28]:
X = dataset.iloc[:, 3:-1].values
print (X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [29]:
y = dataset.iloc[:, -1].values
print (y)


[1 0 1 ... 1 1 0]


In [30]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print (X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [31]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print (X)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [32]:
pd.DataFrame(X)

0    1    2    3  4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

In [33]:
print (X.shape)

(10000, 12)


In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print (X.shape)
print (X_train.shape)
print (X_test.shape)


(10000, 12)
(8000, 12)
(2000, 12)


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
display (pd.DataFrame(X_train ))


0         1         2         3         4         5         6   \
0    -1.014607 -0.569844  1.743090  0.169582 -1.091687 -0.464608  0.006661   
1    -1.014607  1.754865 -0.573694 -2.304559  0.916013  0.301026 -1.377440   
2     0.985604 -0.569844 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415   
3    -1.014607 -0.569844  1.743090  0.035566  0.916013  0.109617  0.006661   
4    -1.014607 -0.569844  1.743090  2.056114 -1.091687  1.736588  1.044737   
...        ...       ...       ...       ...       ...       ...       ...   
7995 -1.014607  1.754865 -0.573694 -0.582970 -1.091687 -0.656016 -0.339364   
7996 -1.014607 -0.569844  1.743090  1.478815 -1.091687 -1.613058 -0.339364   
7997  0.985604 -0.569844 -0.573694  0.901515  0.916013 -0.368904  0.006661   
7998 -1.014607 -0.569844  1.743090 -0.624205 -1.091687 -0.081791  1.390762   
7999 -1.014607  1.754865 -0.573694 -0.284011 -1.091687  0.875251 -1.377440   

            7         8         9         10        11  
0    -1.215717  0.809503  0.642595 -1.032270  1.106432  
1    -0.006312 -0.921591  0.642595  0.968738 -0.748664  
2     0.579935 -0.921591  0.642595 -1.032270  1.485335  
3     0.473128 -0.921591  0.642595 -1.032270  1.276528  
4     0.810193  0.809503  0.642595  0.968738  0.558378  
...        ...       ...       ...       ...       ...  
7995  0.703104  0.809503  0.642595  0.968738  1.091330  
7996  0.613060 -0.921591  0.642595  0.968738  0.131760  
7997  1.361474  0.809503  0.642595 -1.032270  1.412320  
7998 -1.215717  0.809503  0.642595  0.968738  0.844321  
7999  0.511364 -0.921591  0.642595 -1.032270  0.324725  

[8000 rows x 12 columns]

In [36]:

X_test = sc.transform(X_test)
display (pd.DataFrame(X_test ))



0         1         2         3         4         5         6   \
0    -1.014607  1.754865 -0.573694 -0.552043 -1.091687 -0.368904  1.044737   
1     0.985604 -0.569844 -0.573694 -1.314903 -1.091687  0.109617 -1.031415   
2    -1.014607 -0.569844  1.743090  0.571630 -1.091687  0.301026  1.044737   
3     0.985604 -0.569844 -0.573694  1.416961  0.916013 -0.656016 -0.339364   
4    -1.014607  1.754865 -0.573694  0.571630  0.916013 -0.081791  0.006661   
...        ...       ...       ...       ...       ...       ...       ...   
1995  0.985604 -0.569844 -0.573694 -0.263393 -1.091687 -1.421650 -1.377440   
1996  0.985604 -0.569844 -0.573694 -0.665441 -1.091687 -0.368904  0.698712   
1997 -1.014607 -0.569844  1.743090 -0.747912  0.916013 -0.273200 -1.377440   
1998 -1.014607  1.754865 -0.573694 -0.005670  0.916013 -0.464608 -0.339364   
1999 -1.014607  1.754865 -0.573694 -0.799457  0.916013 -0.847425  1.044737   

            7         8         9         10        11  
0     0.879303 -0.921591  0.642595  0.968738  1.610857  
1     0.429722 -0.921591  0.642595 -1.032270  0.495870  
2     0.308583 -0.921591  0.642595  0.968738 -0.424787  
3     0.575336 -0.921591 -1.556190 -1.032270 -0.187777  
4     1.389611  0.809503  0.642595  0.968738  0.616842  
...        ...       ...       ...       ...       ...  
1995 -1.215717  0.809503  0.642595  0.968738  1.404319  
1996 -1.215717  0.809503  0.642595 -1.032270 -0.511196  
1997  1.297455  0.809503  0.642595 -1.032270  0.718885  
1998  1.059752 -0.921591  0.642595  0.968738 -1.545078  
1999  0.820263 -0.921591  0.642595 -1.032270  1.612559  

[2000 rows x 12 columns]

In [37]:
ann = tf.keras.models.Sequential()

In [38]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [40]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [41]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [42]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


In [43]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [45]:

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7960 - loss: 0.5039
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7960 - loss: 0.4479
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4324
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8171 - loss: 0.4227
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8235 - loss: 0.4144
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8276 - loss: 0.4068
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8316 - loss: 0.3987
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8354 - loss: 0.3887
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8410 - loss: 0.3779
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8469 - loss: 0.3666
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8521 - loss: 0.3578
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [44]:
8000/32

250.0

In [46]:
print  (ann.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (32, 12)                    │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (32, 6)                     │              78 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (32, 6)                     │              42 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (32, 1)                     │               7 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 851 (3.33 KB)

 Trainable params: 283 (1.11 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 568 (2.22 KB)

None


In [47]:
12 *12+12

156

In [48]:
12*6+6

78

In [49]:
6*6+6

42

In [50]:
6*1+1

7

In [51]:
156+78+42+7

283

In [52]:
y_pred = ann.predict(X_test)
print (y_pred)


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[0.2931281 ]
 [0.27704677]
 [0.13703178]
 ...
 [0.15960342]
 [0.131616  ]
 [0.19036211]]


In [53]:
y_pred = (y_pred > 0.5)   
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [54]:
y_pred = (y_pred > 0.5) 
y_pred 

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], shape=(2000, 1))

In [55]:
result = np.concatenate((X_test, y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1)
result = pd.DataFrame(result )
display (result)

0         1         2         3         4         5         6   \
0    -1.014607  1.754865 -0.573694 -0.552043 -1.091687 -0.368904  1.044737   
1     0.985604 -0.569844 -0.573694 -1.314903 -1.091687  0.109617 -1.031415   
2    -1.014607 -0.569844  1.743090  0.571630 -1.091687  0.301026  1.044737   
3     0.985604 -0.569844 -0.573694  1.416961  0.916013 -0.656016 -0.339364   
4    -1.014607  1.754865 -0.573694  0.571630  0.916013 -0.081791  0.006661   
...        ...       ...       ...       ...       ...       ...       ...   
1995  0.985604 -0.569844 -0.573694 -0.263393 -1.091687 -1.421650 -1.377440   
1996  0.985604 -0.569844 -0.573694 -0.665441 -1.091687 -0.368904  0.698712   
1997 -1.014607 -0.569844  1.743090 -0.747912  0.916013 -0.273200 -1.377440   
1998 -1.014607  1.754865 -0.573694 -0.005670  0.916013 -0.464608 -0.339364   
1999 -1.014607  1.754865 -0.573694 -0.799457  0.916013 -0.847425  1.044737   

            7         8         9         10        11   12   13  
0     0.879303 -0.921591  0.642595  0.968738  1.610857  0.0  0.0  
1     0.429722 -0.921591  0.642595 -1.032270  0.495870  1.0  0.0  
2     0.308583 -0.921591  0.642595  0.968738 -0.424787  0.0  0.0  
3     0.575336 -0.921591 -1.556190 -1.032270 -0.187777  0.0  0.0  
4     1.389611  0.809503  0.642595  0.968738  0.616842  0.0  0.0  
...        ...       ...       ...       ...       ...  ...  ...  
1995 -1.215717  0.809503  0.642595  0.968738  1.404319  0.0  0.0  
1996 -1.215717  0.809503  0.642595 -1.032270 -0.511196  0.0  0.0  
1997  1.297455  0.809503  0.642595 -1.032270  0.718885  0.0  0.0  
1998  1.059752 -0.921591  0.642595  0.968738 -1.545078  0.0  0.0  
1999  0.820263 -0.921591  0.642595 -1.032270  1.612559  0.0  0.0  

[2000 rows x 14 columns]

In [57]:
!pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]



In [58]:
from openpyxl import Workbook

from openpyxl import Workbook
result.to_excel ("21_Jan_ann_Churn_Modelling.xlsx")


In [59]:

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print ("Accuracy")
print (accuracy_score(y_test, y_pred))
print ()
print ('Classification Report')
print (classification_report (y_test, y_pred,zero_division = 0))
print ()
cm = confusion_matrix(y_test, y_pred)
print(cm)



Accuracy
0.86

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1595
           1       0.72      0.50      0.59       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.75      2000
weighted avg       0.85      0.86      0.85      2000


[[1518   77]
 [ 203  202]]


In [60]:
X_STD = sc.transform(X)
y_full_pred = ann.predict(X_STD )
y_full_pred = (y_full_pred > 0.5)   
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print ("Accuracy")
print (accuracy_score(y, y_full_pred))
print ()
print ('Classification Report')
print (classification_report (y, y_full_pred,zero_division = 0))
print ()
cm = confusion_matrix(y,y_full_pred)
print(cm)


313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy
0.8694

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      7963
           1       0.78      0.50      0.61      2037

    accuracy                           0.87     10000
   macro avg       0.83      0.73      0.76     10000
weighted avg       0.86      0.87      0.86     10000


[[7683  280]
 [1026 1011]]


In [64]:
print (pd.DataFrame (X).head(2))

    0    1    2    3  4   5  6         7  8  9  10         11
0  1.0  0.0  0.0  619  0  42  2       0.0  1  1  1  101348.88
1  0.0  0.0  1.0  608  0  41  1  83807.86  1  0  1  112542.58


In [66]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[False]]


In [65]:
sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

array([[ 0.98560362, -0.5698444 , -0.57369368, -0.52111599,  0.91601335,
         0.10961719, -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,
         0.9687384 , -0.87203322]])