In [1]:

from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
import os
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report	



In [2]:
os.chdir('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 14\\')

In [3]:
pwd

'C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 14'

In [4]:
dataset = pd.read_csv('Boost_mushrooms.csv')
display (dataset)


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [5]:
print (dataset.shape)

(8124, 23)


In [6]:
print (dataset.isna().sum())

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64


In [7]:
print (dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [8]:
dataset.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [9]:
for label in dataset.columns:
    print (label)


class
cap-shape
cap-surface
cap-color
bruises
odor
gill-attachment
gill-spacing
gill-size
gill-color
stalk-shape
stalk-root
stalk-surface-above-ring
stalk-surface-below-ring
stalk-color-above-ring
stalk-color-below-ring
veil-type
veil-color
ring-number
ring-type
spore-print-color
population
habitat


In [10]:
for label in dataset.columns:
    dataset[label] = LabelEncoder().fit(dataset[label]).transform(dataset[label] )
    
display (dataset)


class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [11]:
x = dataset.drop(['class'],axis =1)
display (x)


cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0             5            2          4        1     6                1   
1             5            2          9        1     0                1   
2             0            2          8        1     3                1   
3             5            3          8        1     6                1   
4             5            2          3        0     5                1   
...         ...          ...        ...      ...   ...              ...   
8119          3            2          4        0     5                0   
8120          5            2          4        0     5                0   
8121          2            2          4        0     5                0   
8122          3            3          4        0     8                1   
8123          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0                0          1           4            0  ...   
1                0          0           4            0  ...   
2                0          0           5            0  ...   
3                0          1           5            0  ...   
4                1          0           4            1  ...   
...            ...        ...         ...          ...  ...   
8119             0          0          11            0  ...   
8120             0          0          11            0  ...   
8121             0          0           5            0  ...   
8122             0          1           0            1  ...   
8123             0          0          11            0  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 22 columns]

In [12]:
y = dataset['class']
display (y)


0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int64

In [13]:
x_train , x_test,y_train,y_test = train_test_split (x,y,test_size = 0.3)
print (x.shape)
print (x_train.shape)
print (x_test.shape)
print (y_train.shape)
print (y_test.shape)


(8124, 22)
(5686, 22)
(2438, 22)
(5686,)
(2438,)


In [14]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
print (lr)


LogisticRegression()


In [15]:
AdaBoost= AdaBoostClassifier(estimator = lr , n_estimators = 400, learning_rate =1)
lrboostmodel= AdaBoost.fit(x_train,y_train)
print (lrboostmodel)


AdaBoostClassifier(estimator=LogisticRegression(), learning_rate=1,
                   n_estimators=400)


In [16]:
lr_pred = lrboostmodel.predict(x_test)
display (lr_pred)


array([1, 1, 1, ..., 0, 1, 0])

In [17]:
print (accuracy_score(y_test,lr_pred))

0.9138638228055783


In [18]:

print (classification_report(y_test,lr_pred,zero_division=0))



              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1269
           1       0.94      0.88      0.91      1169

    accuracy                           0.91      2438
   macro avg       0.92      0.91      0.91      2438
weighted avg       0.92      0.91      0.91      2438



In [19]:
cm = confusion_matrix(y_test,lr_pred)
print (cm)


[[1201   68]
 [ 142 1027]]


In [20]:
lr_pred = lrboostmodel.predict(x)
display (lr_pred)


array([0, 0, 0, ..., 0, 1, 0])

In [21]:
print (accuracy_score(y,lr_pred))

0.9039881831610044


In [22]:

print (classification_report(y,lr_pred,zero_division=0))


              precision    recall  f1-score   support

           0       0.89      0.93      0.91      4208
           1       0.92      0.88      0.90      3916

    accuracy                           0.90      8124
   macro avg       0.91      0.90      0.90      8124
weighted avg       0.90      0.90      0.90      8124



In [23]:
cm = confusion_matrix(y,lr_pred)
print (cm)


[[3915  293]
 [ 487 3429]]


In [24]:
dt_model = DecisionTreeClassifier (criterion = 'entropy', max_depth = 1)
print (dt_model)


DecisionTreeClassifier(criterion='entropy', max_depth=1)


In [25]:
AdaBoost= AdaBoostClassifier(estimator = dt_model, n_estimators = 400, learning_rate =1)
boostmodel= AdaBoost.fit(x_train,y_train)
print (boostmodel)


AdaBoostClassifier(estimator=DecisionTreeClassifier(criterion='entropy',
                                                    max_depth=1),
                   learning_rate=1, n_estimators=400)


In [26]:
dt_pred = boostmodel.predict(x_test)
print (dt_pred)


[1 1 1 ... 0 1 0]


In [27]:
print (accuracy_score(y_test,dt_pred))

1.0


In [28]:

print (classification_report(y_test,dt_pred,zero_division=0))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1269
           1       1.00      1.00      1.00      1169

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438



In [29]:
cm = confusion_matrix(y_test,dt_pred)
print (cm)


[[1269    0]
 [   0 1169]]


In [30]:
dt_pred = boostmodel.predict(x)
print (dt_pred)


[1 0 0 ... 0 1 0]


In [31]:
print (accuracy_score(y,dt_pred))

1.0


In [32]:

print (classification_report(y,dt_pred,zero_division=0))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4208
           1       1.00      1.00      1.00      3916

    accuracy                           1.00      8124
   macro avg       1.00      1.00      1.00      8124
weighted avg       1.00      1.00      1.00      8124



In [33]:
cm = confusion_matrix(y,dt_pred)
print (cm)


[[4208    0]
 [   0 3916]]


In [34]:

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier (criterion = 'entropy')
dt.fit (x_train,y_train)
print (dt)



DecisionTreeClassifier(criterion='entropy')


In [35]:
dt_pred = dt.predict (x_test)
print (dt_pred)


[1 1 1 ... 0 1 0]


In [36]:
print (accuracy_score(y_test,dt_pred))

1.0


In [37]:

print (classification_report(y_test,dt_pred,zero_division=0))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1269
           1       1.00      1.00      1.00      1169

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438



In [38]:
cm = confusion_matrix(y_test,dt_pred)
print (cm)


[[1269    0]
 [   0 1169]]
