In [16]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [17]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 12\\')

In [18]:
df= pd.read_csv('Bank Data Dimension Reduction.csv')
print (df)


     Index  Interest  Credit  Gender  Previous  Duration Churn
0        0   17546.0       1     0.0       0.0      48.0    NO
1        1   30085.1       3     1.0       1.0      40.0   YES
2        2   16575.4       0     0.0       1.0      51.0   YES
3        3   20375.4       3     0.0       0.0      23.0   YES
4        4   50576.3       0     0.0       0.0      57.0    NO
..     ...       ...     ...     ...       ...       ...   ...
595    595   47025.0       2     0.0       1.0       NaN   YES
596    596    9672.3       0     0.0       1.0       NaN   YES
597    597   15976.3       0     0.0       1.0       NaN    NO
598    598   14711.8       0     1.0       0.0      29.0    NO
599    599   26671.6       0     1.0       1.0      38.0   YES

[600 rows x 7 columns]


In [19]:
print (df.isna().sum())
print ()


Index        0
Interest    68
Credit       0
Gender      21
Previous     7
Duration    70
Churn        0
dtype: int64



In [20]:
print (df.groupby('Gender').size())

Gender
0.0    290
1.0    289
dtype: int64


In [21]:
df['Gender'] = df['Gender'].fillna(0)
print ()


In [22]:
print (df.groupby('Gender').size())

Gender
0.0    311
1.0    289
dtype: int64


In [23]:
290+21

311

In [24]:
print (df.groupby('Previous').size())

Previous
0.0    302
1.0    291
dtype: int64


In [25]:
print (df.isna().sum())
print ()


Index        0
Interest    68
Credit       0
Gender       0
Previous     7
Duration    70
Churn        0
dtype: int64



In [26]:
df['Previous'] = df['Previous'].fillna(0)
print (df.isna().sum())
print ()


Index        0
Interest    68
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64



In [27]:
df['Interest'].mean()

np.float64(27630.171616541356)

In [28]:
print (df.isna().sum())
print ()


Index        0
Interest    68
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64



In [29]:
df['Interest'] = df['Interest'].fillna(df['Interest'].mean())
print (df.isna().sum())
print ()


Index        0
Interest     0
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64



In [30]:
df['Duration'].mean()

np.float64(42.64528301886792)

In [31]:
df['Duration'].median()

43.0

In [32]:
print (df.isna().sum())
df['Duration'] =df['Duration'].fillna(df['Duration'].median())
print ()
print (df.isna().sum())


Index        0
Interest     0
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64

Index       0
Interest    0
Credit      0
Gender      0
Previous    0
Duration    0
Churn       0
dtype: int64


In [33]:
print(df.dtypes)

Index         int64
Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object


In [34]:
df['Gender'] = df['Gender']. astype('category')
print ()
print(df.dtypes)



Index          int64
Interest     float64
Credit         int64
Gender      category
Previous     float64
Duration     float64
Churn         object
dtype: object


In [35]:
print(df.dtypes)
df['Previous'] = df['Previous']. astype('category')
print ('********')
print(df.dtypes)


Index          int64
Interest     float64
Credit         int64
Gender      category
Previous     float64
Duration     float64
Churn         object
dtype: object
********
Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn         object
dtype: object


In [36]:
print(df.dtypes)
df['Churn'] = df['Churn']. astype('category')
df['Churn'] = df['Churn'].cat.codes
print ('********')
print(df.dtypes)


Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn         object
dtype: object
********
Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn           int8
dtype: object


In [37]:
df

Index  Interest  Credit Gender Previous  Duration  Churn
0        0   17546.0       1    0.0      0.0      48.0      0
1        1   30085.1       3    1.0      1.0      40.0      1
2        2   16575.4       0    0.0      1.0      51.0      1
3        3   20375.4       3    0.0      0.0      23.0      1
4        4   50576.3       0    0.0      0.0      57.0      0
..     ...       ...     ...    ...      ...       ...    ...
595    595   47025.0       2    0.0      1.0      43.0      1
596    596    9672.3       0    0.0      1.0      43.0      1
597    597   15976.3       0    0.0      1.0      43.0      0
598    598   14711.8       0    1.0      0.0      29.0      0
599    599   26671.6       0    1.0      1.0      38.0      1

[600 rows x 7 columns]

In [38]:
df

Index  Interest  Credit Gender Previous  Duration  Churn
0        0   17546.0       1    0.0      0.0      48.0      0
1        1   30085.1       3    1.0      1.0      40.0      1
2        2   16575.4       0    0.0      1.0      51.0      1
3        3   20375.4       3    0.0      0.0      23.0      1
4        4   50576.3       0    0.0      0.0      57.0      0
..     ...       ...     ...    ...      ...       ...    ...
595    595   47025.0       2    0.0      1.0      43.0      1
596    596    9672.3       0    0.0      1.0      43.0      1
597    597   15976.3       0    0.0      1.0      43.0      0
598    598   14711.8       0    1.0      0.0      29.0      0
599    599   26671.6       0    1.0      1.0      38.0      1

[600 rows x 7 columns]

In [39]:
x = df.iloc[:,1:6].values
print (x)


[[1.75460e+04 1.00000e+00 0.00000e+00 0.00000e+00 4.80000e+01]
 [3.00851e+04 3.00000e+00 1.00000e+00 1.00000e+00 4.00000e+01]
 [1.65754e+04 0.00000e+00 0.00000e+00 1.00000e+00 5.10000e+01]
 ...
 [1.59763e+04 0.00000e+00 0.00000e+00 1.00000e+00 4.30000e+01]
 [1.47118e+04 0.00000e+00 1.00000e+00 0.00000e+00 2.90000e+01]
 [2.66716e+04 0.00000e+00 1.00000e+00 1.00000e+00 3.80000e+01]]


In [40]:
y = df.iloc[:,6].values
print (y)


[0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1
 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1
 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1
 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1
 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 0 1 0 1 1 1 0
 1 1 0 0 0 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0
 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 1
 1 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1
 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 0 0 0 1 0 

In [41]:

from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x = sc_x.fit_transform(x)
print (x)


[[-0.83481117 -0.01104933 -0.96398156 -0.97043679  0.39357468]
 [ 0.20322955  1.88312118  1.03736424  1.03046381 -0.19900953]
 [-0.91516162 -0.95813458 -0.96398156  1.03046381  0.61579376]
 ...
 [-0.9647577  -0.95813458 -0.96398156  1.03046381  0.02320955]
 [-1.06943845 -0.95813458  1.03736424 -0.97043679 -1.01381282]
 [-0.07935469 -0.95813458  1.03736424  1.03046381 -0.34715558]]


In [42]:
from sklearn.decomposition import PCA
pca = PCA(n_components = None)
PCA_X = pca.fit_transform(x)
print (pd.DataFrame(PCA_X))


            0         1         2         3         4
0   -0.389348 -1.263066  0.561508 -0.217232 -0.783283
1    0.258535  2.122143  0.938872 -0.534113  0.167161
2    0.008022 -0.424435 -0.082947  1.681945 -1.053486
3   -1.330230 -0.276444  2.208619 -0.862935  0.660123
4    1.864882 -1.788824 -0.570752 -0.196370  0.692477
..        ...       ...       ...       ...       ...
595  1.504013  0.377072  1.179921  0.631916  1.118015
596 -0.791650 -0.348038  0.038977  1.813712 -1.039632
597 -0.432636 -0.359121 -0.021943  1.753198 -0.670900
598 -1.813000 -0.205058 -1.207329 -0.564423 -0.046633
599 -0.290127  0.958035 -1.267196  0.749886  0.112675

[600 rows x 5 columns]


In [43]:

print (pca.explained_variance_ratio_)


[0.33943997 0.20168854 0.20083191 0.18998087 0.06805872]


In [44]:

from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
PCA_X = pca.fit_transform(x)
print (pd.DataFrame(PCA_X))



            0         1
0   -0.389348 -1.263066
1    0.258535  2.122143
2    0.008022 -0.424435
3   -1.330230 -0.276444
4    1.864882 -1.788824
..        ...       ...
595  1.504013  0.377072
596 -0.791650 -0.348038
597 -0.432636 -0.359121
598 -1.813000 -0.205058
599 -0.290127  0.958035

[600 rows x 2 columns]


In [45]:
print (pca.explained_variance_ratio_)

[0.33943997 0.20168854]


In [46]:

from sklearn.model_selection import train_test_split
PCA_X_train,PCA_X_test, y_train,y_test = train_test_split(PCA_X,y,test_size=0.2,random_state=42)
print (PCA_X.shape)
print (PCA_X_train.shape)
print (PCA_X_test.shape)



(600, 2)
(480, 2)
(120, 2)


In [47]:
print (pd.DataFrame(PCA_X_train))

            0         1
0    1.738955 -0.502162
1    0.204813  0.417182
2   -0.468288  0.944145
3   -0.226301 -0.307319
4    0.345016  1.734410
..        ...       ...
475 -2.598207 -0.129107
476  1.405671  0.834581
477  3.120727 -1.096250
478 -1.734504  1.895565
479 -0.723088  0.945547

[480 rows x 2 columns]


In [48]:
from sklearn.linear_model import LogisticRegression 
logmodel = LogisticRegression()
logmodel= logmodel.fit (PCA_X_train,y_train)


In [49]:
y_pred = logmodel.predict(PCA_X_test)
print (y_pred)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


In [51]:
print (y_test)

[1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 0 0 1 0 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 0 1 1]


In [52]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)


[[ 0 28]
 [ 0 92]]


In [53]:

print (accuracy_score (y_test,y_pred))


0.7666666666666667


In [54]:
from sklearn.tree import DecisionTreeClassifier 
dt = DecisionTreeClassifier ()
dt= dt.fit (PCA_X_train,y_train)



In [55]:
y_pred = dt.predict(PCA_X_test)
print (y_pred)


[1 0 0 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1
 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 0 0 1 1 1]


In [56]:
print (accuracy_score (y_test,y_pred))
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)


0.6416666666666667
[[ 6 22]
 [21 71]]


In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)


In [58]:
from sklearn.linear_model import LogisticRegression 
logmodelNOPCA = LogisticRegression()
logmodelNOPCA= logmodelNOPCA.fit (x_train,y_train)


In [59]:
y_pred = logmodelNOPCA.predict(x_test)
print (y_pred)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


In [60]:
cm = confusion_matrix (y_test, y_pred)
print (cm)


[[ 0 28]
 [ 0 92]]


In [61]:

print (accuracy_score (y_test,y_pred))



0.7666666666666667


In [62]:

from sklearn.tree import DecisionTreeClassifier 
dtnopca = DecisionTreeClassifier ()
dtnopca = dtnopca .fit (x_train,y_train)



In [63]:
y_pred = dtnopca.predict(x_test)
print (y_pred)


[1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1
 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1
 0 1 0 1 0 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1 1 1
 1 1 1 0 1 1 0 1 1]


In [64]:
print (accuracy_score (y_test,y_pred))
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)


0.65
[[ 7 21]
 [21 71]]
