In [13]:
 # 1.Array Creation

 ## Create a 3D array of shape (4, 5, 6) filled with consecutive integers starting from 1.
 ## Generate an array with random floats sampled from a normal distribution with mean 10
 # and standard deviation 5, shape (10, 10).
 ##Create a 2D array of shape (8, 8) where the diagonal elements are 1 and others are 0.
import numpy as np
arr_3d = np.arange(1, 4*5*6 + 1).reshape(4, 5, 6)
print("3D Array (4,5,6):\n", arr_3d)

arr_normal = np.random.normal(loc=10, scale=5, size=(10, 10))
print("\nNormal Dist Array (10,10):\n", arr_normal)

arr_identity = np.eye(8, dtype=int)
print("\nDiagonal 8x8 Array:\n", arr_identity)


3D Array (4,5,6):
 [[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]]

 [[ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]

Normal Dist Array (10,10):
 [[-0.85589243 11.45467228  2.92039575  3.13878924 15.23616367  8.78373982
   0.91732341 10.11018793 14.0801096   4.16059237]
 [10.80854141 11.34034778 14.65244258  6.77933127 14.316393   11.32928491
   1.2011921   2.86152364 14.38256213  0.1584106 ]
 [13.82147112  8.74017498  6.61973112 19.59635041  8.59341325  7.65733146
  -2.59847761 13.05903404  8.1664501   4.960115  ]
 [21.3681

In [34]:
# 2. Operations
# # Perform element-wise multiplication and division between two randomly generated arrays
#  of the same shape.
#  #Multiply a 2D array by a 1D array using broadcasting rules and explain the result.
# 3 Compute the dot product and matrix multiplication of two compatible matrices using
#  np.dot and @ operator.
a =np.random.randint(1,10, size= (2,3))
print("a : \n",a)
print("b : \n",b)
b=np.random.randint(1,10 ,size= (2,3))
c = a*b
print("a multiple b :\n",c,"\n")

# 2
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_1d = np.array([10, 20, 30])

broadcast_result = arr_2d * arr_1d
print("broadcast_result:\n",broadcast_result)

x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
              [7, 8]])

print("Dot Product:\n",np.dot(x, y)) 
print("Matrix Multiplication using @ :\n",x @ y )   

a : 
 [[2 1 9]
 [2 8 9]]
b : 
 [[5 5 8]
 [6 5 1]]
a multiple b :
 [[10  2 36]
 [14  8 54]] 

broadcast_result:
 [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication using @ :
 [[19 22]
 [43 50]]


In [44]:
# 3. Indexing & Slicing
# #Given a 2D array of shape (10, 10), use advanced integer indexing to extract elements at
# random row and column indices, including duplicate indices.
# # Extract a sub-array excluding the border rows and columns (i.e., inner (8, 8) block).
# #Reverse the rows of a matrix without changing the columns using slicing.
arr = np.arange(100).reshape(10, 10)
arr1 = np.random.randint(1,10 ,size= 5)
arr2 = np.random.randint(1,10 ,size= 5)

print("row :\n", arr1,"\n")
print("column :\n", arr2,"\n")

mer = arr[arr1, arr2]
print(mer)

inner = arr[1:-1, 1:-1]
print("Inner 8x8 block:\n", inner)

rev_rows = arr[::-1, :]
print("Rows reversed and columns unchanged:\n", rev_rows)

row :
 [9 9 1 5 5] 

column :
 [7 5 3 4 7] 

[97 95 13 54 57]
Inner 8x8 block:
 [[11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]
 [31 32 33 34 35 36 37 38]
 [41 42 43 44 45 46 47 48]
 [51 52 53 54 55 56 57 58]
 [61 62 63 64 65 66 67 68]
 [71 72 73 74 75 76 77 78]
 [81 82 83 84 85 86 87 88]]
Rows reversed (columns unchanged):
 [[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [45]:
#4. Reshaping & Manipulating Arrays
## Reshape a (100,) array into (10, 10) and then flatten it back, verifying the integrity of the
#  data.
##Concatenate three arrays along different axes; demonstrate horizontal and vertical
# stacking with appropriate code.
## Split a (12, 12) matrix vertically into 3 equal parts using NumPy splitting functions.

# Create array of shape (100,)
arr = np.arange(100)
print("Original Shape:", arr.shape)

# Reshape to (10, 10)
reshaped = arr.reshape(10, 10)
print("Reshaped (10x10):\n", reshaped)

# Flatten back to 1D
flattened = reshaped.flatten()
print("Flattened Shape:", flattened.shape)

# Integrity check
print("Integrity Check (same data):", np.array_equal(arr, flattened))


# Create 3 arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])

print("Array A:\n", a)
print("Array B:\n", b)
print("Array C:\n", c)

# Horizontal stacking
h_stack = np.hstack((a, b, c))
print("\nHorizontal Stack:\n", h_stack)

# Vertical stacking
v_stack = np.vstack((a, b, c))
print("\nVertical Stack:\n", v_stack)

# Concatenate axis=0
con0 = np.concatenate((a, b, c), axis=0)
print("\nConcatenate axis=0:\n", con0)

# Concatenate axis=1
con1 = np.concatenate((a, b, c), axis=1)
print("\nConcatenate axis=1:\n", con1)

# Create 12x12 matrix
matrix = np.arange(144).reshape(12, 12)
print("Original 12x12 Matrix:\n", matrix)

# Split vertically (columns)
vertical_parts = np.split(matrix, 3, axis=1)

print("\nVertical Part 1:\n", vertical_parts[0])
print("\nVertical Part 2:\n", vertical_parts[1])
print("\nVertical Part 3:\n", vertical_parts[2])


Original Shape: (100,)
Reshaped (10x10):
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Flattened Shape: (100,)
Integrity Check (same data): True
Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Array C:
 [[ 9 10]
 [11 12]]

Horizontal Stack:
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

Vertical Stack:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Concatenate axis=0:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Concatenate axis=1:
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

=== TASK 3: Split 12x12 Matrix Vertically into 3 Parts ===
Original 12x12 Matrix:
 [[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29 

In [46]:
# 5. Aggregation Functions
## Calculate the mean, median, and standard deviation of each column in a (15, 10) array. 
##Find the indices of minimum and maximum values along each row.
##Compute the cumulative sum and cumulative product of elements along the flattened
# array.

arr = np.random.randint(1, 100, size=(15, 10))
print("Array (15x10):\n", arr)

# Column wise
mean_cols = np.mean(arr, axis=0)
median_cols = np.median(arr, axis=0)
std_cols = np.std(arr, axis=0)

print("\nColumn-wise Mean:\n", mean_cols)
print("\nColumn-wise Median:\n", median_cols)
print("\nColumn-wise Std Dev:\n", std_cols)


min_indices = np.argmin(arr, axis=1)
max_indices = np.argmax(arr, axis=1)

print("\nIndices of Minimum Value in Each Row:\n", min_indices)
print("\nIndices of Maximum Value in Each Row:\n", max_indices)

flat = arr.flatten()

cum_sum = np.cumsum(flat)
cum_prod = np.cumprod(flat)

print("\nCumulative Sum of Flattened Array:\n", cum_sum)
print("\nCumulative Product of Flattened Array:\n", cum_prod)


Array (15x10):
 [[66 26  7 58 79 73 47 34 15 71]
 [99  6 40 45 82 22 36 70 81 72]
 [65 11 21 26 66 27 35 10 33 48]
 [86 65 43 78 39 35  9 80  4 11]
 [63 37 42 94 97 19 88 10 63 40]
 [86 10 27 58 73 75 79 40 73 36]
 [14 56 40 12 61  1 67  6 40  8]
 [44  6 50 51 26  6 77 21 47 69]
 [79 68 67 33 24 79 29 49 85 61]
 [19  9 94 38 95 13  3 10 29 27]
 [68 98 36 73 28 67 38  4 89 33]
 [20 64 38 32 33  3 37 12 24 93]
 [22  3 71 67 15 12  9 30 61 56]
 [54 64  3 54 66 38  5 51 38 18]
 [14  9 31 15 44 13 50 71 87 91]]

Column-wise Mean:
 [53.26666667 35.46666667 40.66666667 48.93333333 55.2        32.2
 40.6        33.2        51.26666667 48.93333333]

Column-wise Median:
 [63. 26. 40. 51. 61. 22. 37. 30. 47. 48.]

Column-wise Std Dev:
 [28.20984856 29.91291063 22.80545744 22.64646158 26.15645236 26.95972305
 26.78009211 25.03650668 26.92078916 26.30960957]

Indices of Minimum Value in Each Row:
 [2 1 7 8 7 1 5 1 4 6 7 5 1 2 1]

Indices of Maximum Value in Each Row:
 [4 0 4 0 4 0 6 6 8 4 1 9 2 4 9

In [47]:
# 6. Handling Missing Values
# #Create an array of 200 random floats and randomly assign 10% of values to np.nan. 
# #Write code to detect and count the missing values. Replace missing values with the mean of their respective columns.
# #Demonstrate removing rows or columns containing any missing values.

arr = np.random.random(200)


num_missing = int(0.10 * arr.size)     
missing_indices = np.random.choice(arr.size, num_missing, replace=False)

arr[missing_indices] = np.nan
print("Array with NaN values:\n", arr)


arr = arr.reshape(20, 10)
print("\nReshaped (20x10):\n", arr)

missing_mask = np.isnan(arr)

missing_count = np.sum(missing_mask)

print("\nMissing Value Mask:\n", missing_mask)
print("\nTotal Missing Values:", missing_count)

col_means = np.nanmean(arr, axis=0)


arr_filled = np.where(np.isnan(arr), col_means, arr)

print("\nColumn Means:\n", col_means)
print("\nArray After Replacing NaN with Column Means:\n", arr_filled)


rows_removed = arr[~np.isnan(arr).any(axis=1)]
print("\nRows with no missing values:\n", rows_removed)

cols_removed = arr[:, ~np.isnan(arr).any(axis=0)]
print("\nColumns with no missing values:\n", cols_removed)


Array with NaN values:
 [0.66071982 0.82033707 0.08868931 0.0957428  0.7086335  0.89137424
 0.56885846 0.0066281  0.99482521 0.19816098 0.74859945 0.21856922
 0.76029112 0.96564311 0.62464094 0.8994761  0.88075098 0.07575943
 0.12740752 0.03529099 0.65788    0.67470503 0.80155621 0.86543897
 0.56651575 0.61594737 0.97910997 0.04013765 0.8872871  0.59567781
 0.66166317 0.57132    0.7213497  0.98620299 0.9886538         nan
 0.60191136        nan 0.28226073 0.23325136 0.98140561 0.81913505
        nan 0.40294592 0.99076751 0.49413362 0.82647809 0.32732115
 0.95446704 0.70438255 0.60330195        nan 0.92630781 0.59816846
 0.32289112 0.21048528 0.89820647 0.35458436 0.21018115 0.19624464
 0.78172703 0.28547668 0.29949656 0.17024225 0.83030074 0.81223531
 0.49656979 0.8856675  0.83970861 0.84784384 0.16276923 0.5438622
 0.63966719        nan 0.78914386        nan 0.11328069 0.8923239
 0.61183026 0.27094079 0.12914833 0.92277268 0.97773748 0.49773971
 0.18925772 0.84213715        nan 0.6564