In [2]:
# 1.Create a 2D NumPy array (10×5) with random integers (1–100).
import numpy as np

arr = np.random.randint(1, 101, size=(10, 5)) # size = (num of rows, num of columns)
print(arr)

[[63 64 14 88 57]
 [86 70 25 65 16]
 [48  2 61 14 79]
 [92 30 81  1 27]
 [75 66 61 72 90]
 [45 45 96 37 66]
 [72 67 24  3 24]
 [74  1 25 96 38]
 [71 46 34 75 32]
 [66 71 78 66 22]]


In [6]:
# 2. Replace all values < 50 with 0 and ≥ 50 with 1.
rep = np.where(arr<50,0, 1) # np.where(condition, value_if_true, value_if_false)
print(rep)

[[1 1 0 1 1]
 [1 1 0 1 0]
 [0 0 1 0 1]
 [1 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 1]
 [1 1 0 0 0]
 [1 0 0 1 0]
 [1 0 0 1 0]
 [1 1 1 1 0]]


In [18]:
# 3. Compute mean, standard deviation, variance along rows and columns.
print("---------Rows--------")
row_mean = np.mean(arr, axis = 1)
print("Mean Row = ",row_mean)
row_std = np.std(arr, axis = 1)
print("standard Deviation Row = ",row_std)
row_var = np.var(arr, axis = 1)
print("Variance Row = ",row_var)

# column 
print("------------Column----------")
Column_mean = np.mean(arr, axis = 0)
print("Mean Row = ",Column_mean)
Column_std = np.std(arr, axis = 0)
print("standard Deviation Row = ",Column_std)
Column_var = np.var(arr, axis = 0)
print("Variance Row = ",Column_var)


---------Rows--------
Mean Row =  [57.2 52.4 40.8 46.2 72.8 57.8 38.  46.8 51.6 60.6]
standard Deviation Row =  [24.06158765 27.10424321 28.78471817 34.59132839  9.86711711 21.38597671
 26.88494002 34.09046788 18.16149774 19.79494885]
Variance Row =  [ 578.96  734.64  828.56 1196.56   97.36  457.36  722.8  1162.16  329.84
  391.84]
------------Column----------
Mean Row =  [69.2 46.2 49.9 51.7 45.1]
standard Deviation Row =  [13.97712417 25.65852685 27.53343422 33.46057381 24.73641041]
Variance Row =  [ 195.36  658.36  758.09 1119.61  611.89]


In [26]:
# 4. Generate two arrays A(3×3) and B(3×3) and perform matrix multiplication.
a = np.random.randint(1,10, size =( 3,3))
print("Value of A :\n",a)
b = np.random.randint(1,10, size =( 3,3))
print("Value of B :\n",b)

c = np.matmul(a,b)
print("Mul of A, B :\n",c)

Value of A :
 [[4 8 6]
 [5 4 1]
 [4 3 5]]
Value of B :
 [[5 6 7]
 [8 1 9]
 [8 5 9]]
Mul of A, B :
 [[132  62 154]
 [ 65  39  80]
 [ 84  52 100]]


In [ ]:
# 5. Find the eigenvalues and eigenvectors of a 3×3 matrix.

In [ ]:
# 6. Create a 1D array of 100 random values and normalize it (0–1 scale).