In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os 


In [5]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 16\\')

In [6]:
pwd

'C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 16'

In [7]:
dataset = pd.read_csv('Restaurant_Reviews.tsv')
display (dataset)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 15, saw 3


In [8]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t')
display (dataset)


Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [9]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)
display (dataset)

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [11]:
import nltk  # for stop words
from nltk.corpus import stopwords
nltk.download('stopwords')
all_stopwords = stopwords.words('english')
print (all_stopwords)


['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\noble\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
all_stopwords.remove ('not')

In [25]:
print (all_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she

In [12]:
nltk.download('stopwords') # importing all stopwords 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer # For applying steming in the dataset , to get the root of the word 


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\noble\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
dataset['Review'][2] 

'Not tasty and the texture was just nasty.'

In [14]:
dataset['Review'][3] 

'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.'

In [17]:
dataset['Review'][0]

'Wow... Loved this place.'

In [18]:
import re

In [19]:
review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][0]) 
review

'Wow    Loved this place '

In [20]:
review = review.lower()
review 

'wow    loved this place '

In [22]:
review = review.split() 
review 

['wow', 'loved', 'this', 'place']

In [27]:
ps = PorterStemmer()  

In [28]:
review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
review 

['wow', 'love', 'place']

In [29]:
import re 
# re – Regular expression -  https://docs.python.org/3/library/re.html
import nltk  # for stop words
nltk.download('stopwords') # importing all stopwords 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer # For applying steming in the dataset , to get the root of the word 
corpus = [] # create a list to store all cleaned words 
for i in range(0, 1000):
  # dataset['Review'][i] - source data to prcess - i th record in the data 
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) # Replace punctuations with space, other than letters replace with space 
  review = review.lower()
  review = review.split() # split into different words 
  ps = PorterStemmer()  # get root words
  all_stopwords = stopwords.words('english') # get english stop words 
  all_stopwords.remove('not') # Remove “not” from stop words 
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\noble\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [30]:
corpus

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would not go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place not worth time let alon vega',
 'not like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv

CountVectorizer()

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() # 1500 is decided by statement len(X[0]). Fist execute without max features
X = cv.fit_transform(corpus).toarray()
print (len(X[0]))


1566


In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500) # 1500 is decided by statement len(X[0]). Fist execute without max features
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values # this is dependent variable 
print(len(X[0])) # this gives me the max_features count
print (X.shape)
print (X)
print (y)


In [35]:
import nltk  # for stop words
nltk.download('stopwords') # importing all stopwords 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer # For applying steming in the dataset , to get the root of the word 
corpus = [] # create a list to store all cleaned words 
for i in range(0, 1000):
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) 
  #review = dataset['Review'][i]
  review = review.split() # split into different words 
  review = ' '.join(review)
  corpus.append(review)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\noble\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [36]:
corpus

['Wow Loved this place',
 'Crust is not good',
 'Not tasty and the texture was just nasty',
 'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it',
 'The selection on the menu was great and so were the prices',
 'Now I am getting angry and I want my damn pho',
 'Honeslty it didn t taste THAT fresh',
 'The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer',
 'The fries were great too',
 'A great touch',
 'Service was very prompt',
 'Would not go back',
 'The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced',
 'I tried the Cape Cod ravoli chicken with cranberry mmmm',
 'I was disgusted because I was pretty sure that was human hair',
 'I was shocked because no signs indicate cash only',
 'Highly recommended',
 'Waitress was a little slow in service',
 'This place is not worth your time let alone Vegas',
 'did not like at all',
 'The Burrittos Blah',
 'T

In [72]:
import re 
# re – Regular expression -  https://docs.python.org/3/library/re.html
import nltk  # for stop words
nltk.download('stopwords') # importing all stopwords 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer # For applying steming in the dataset , to get the root of the word 
corpus = [] # create a list to store all cleaned words 
for i in range(0, 1000):
  # dataset['Review'][i] - source data to prcess - i th record in the data 
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) # Replace punctuations with space, other than letters replace with space 
  review = review.lower()
  review = review.split() # split into different words 
  ps = PorterStemmer()  # get root words
  all_stopwords = stopwords.words('english') # get english stop words 
  all_stopwords.remove('not') # Remove “not” from stop words 
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\noble\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [73]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() # 1500 is decided by statement len(X[0]). Fist execute without max features
X = cv.fit_transform(corpus).toarray()
print (len(X[0]))


1566


In [38]:
import re 
# re – Regular expression -  https://docs.python.org/3/library/re.html
import nltk  # for stop words
nltk.download('stopwords') # importing all stopwords 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer # For applying steming in the dataset , to get the root of the word 
corpus = [] # create a list to store all cleaned words 
for i in range(0, 1000):
  # dataset['Review'][i] - source data to prcess - i th record in the data 
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) # Replace punctuations with space, other than letters replace with space 
  review = review.lower()
  review = review.split() # split into different words 
  ps = PorterStemmer()  # get root words
  all_stopwords = stopwords.words('english') # get english stop words 
  all_stopwords.remove('not') # Remove “not” from stop words 
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\noble\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [55]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500) # 1500 is decided by statement len(X[0]). Fist execute without max features
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values # this is dependent variable 
print(len(X[0])) # this gives me the max_features count
print (X.shape)
print (X)
print (y)



1500
(1000, 1500)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 1
 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0
 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1
 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1
 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 1 1
 0 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1
 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1
 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 

In [56]:
pd.DataFrame (X)

0     1     2     3     4     5     6     7     8     9     ...  1490  \
0       0     0     0     0     0     0     0     0     0     0  ...     0   
1       0     0     0     0     0     0     0     0     0     0  ...     0   
2       0     0     0     0     0     0     0     0     0     0  ...     0   
3       0     0     0     0     0     0     0     0     0     0  ...     0   
4       0     0     0     0     0     0     0     0     0     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
995     0     0     0     0     0     0     0     0     0     0  ...     0   
996     0     0     0     0     0     0     0     0     0     0  ...     0   
997     0     0     0     0     0     0     0     0     0     0  ...     0   
998     0     0     0     0     0     0     0     0     0     0  ...     0   
999     0     0     0     0     0     0     0     0     0     0  ...     0   

     1491  1492  1493  1494  1495  1496  1497  1498  1499  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
995     0     0     0     0     0     0     0     0     0  
996     0     0     0     0     0     0     0     0     0  
997     0     0     0     0     0     0     0     0     0  
998     0     0     0     0     0     0     0     0     0  
999     0     0     0     0     0     0     0     0     0  

[1000 rows x 1500 columns]

In [57]:
pd.DataFrame (X).to_csv('08_Jan_bow.csv')

PermissionError: [Errno 13] Permission denied: '08_Jan_bow.csv'

In [ ]:
corpus

In [58]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


In [59]:

print (X.shape)
print (X_train.shape)
print (X_test.shape)


(1000, 1500)
(800, 1500)
(200, 1500)


In [60]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

In [61]:
y_pred = classifier.predict(X_test)
print (y_pred )


[1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1
 0 1 1 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1
 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0
 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 1 1
 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0
 1 0 1 0 1 1 0 1 1 1 0 1 1 1 1]


In [62]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]

In [63]:

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print ('Accuracy:',accuracy_score(y_test, y_pred))
print ()
print(cm)
print (classification_report(y_test, y_pred))



Accuracy: 0.73

[[55 42]
 [12 91]]
              precision    recall  f1-score   support

           0       0.82      0.57      0.67        97
           1       0.68      0.88      0.77       103

    accuracy                           0.73       200
   macro avg       0.75      0.73      0.72       200
weighted avg       0.75      0.73      0.72       200



In [64]:

from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
cm = confusion_matrix(y_test,dt_pred)
print ('Accuracy:', accuracy_score(y_test,dt_pred))
print ()
print(cm)
print (classification_report (y_test,dt_pred))




Accuracy: 0.735

[[76 21]
 [32 71]]
              precision    recall  f1-score   support

           0       0.70      0.78      0.74        97
           1       0.77      0.69      0.73       103

    accuracy                           0.73       200
   macro avg       0.74      0.74      0.73       200
weighted avg       0.74      0.73      0.73       200



In [68]:
new= ['hotel not good', 'food tastier nice', 'chicken not coock properli veg not upto mark','Good Service']

In [69]:
fp = cv.transform(new).toarray()
print (fp.shape)
print (fp)


(4, 1500)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [70]:
classifier.predict (fp)

array([1, 1, 0, 1])

In [71]:
print (dt.predict(fp))

[0 1 0 1]
