In [1]:
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import os


In [2]:
os.chdir ('C:\\Noble\\Training\\KODO\\2025\\Dec 2025\\Dec 2025 Day 16\\')

In [3]:
df = pd.read_csv("Email_Spam_Classification.txt")
display (df)


text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [4]:
print (df.shape)

(5728, 2)


In [5]:
print (df['spam'].value_counts())

spam
0    4360
1    1368
Name: count, dtype: int64


In [6]:
display (df['text'][0])

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  ma

In [7]:

vector = CountVectorizer()
vec = vector.fit_transform(df.text)
bow= vec.toarray()
print (bow.shape)
display (bow)


(5728, 37303)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
label = df.spam
classifier.fit(vec, label)


MultinomialNB()

In [9]:
pred = classifier.predict (vec)
print (pred.shape)
print (pred)


(5728,)
[1 1 1 ... 0 0 0]


In [10]:
from sklearn.metrics import accuracy_score
print (accuracy_score (label,pred))


0.9958100558659218


In [11]:

from sklearn.metrics import classification_report
print(classification_report(label,pred,zero_division=0))



              precision    recall  f1-score   support

           0       1.00      0.99      1.00      4360
           1       0.98      1.00      0.99      1368

    accuracy                           1.00      5728
   macro avg       0.99      1.00      0.99      5728
weighted avg       1.00      1.00      1.00      5728



In [12]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix (label,pred)
print (cm)	


[[4337   23]
 [   1 1367]]


In [13]:
df_pred = pd.DataFrame (pred,columns = ['Spam Prediction']) 
result = pd.concat ([df,df_pred ],axis = 1)
result.to_csv('08_Jan_Spam_Prediction.csv')
display (result)


text  spam  Spam Prediction
0     Subject: naturally irresistible your corporate...     1                1
1     Subject: the stock trading gunslinger  fanny i...     1                1
2     Subject: unbelievable new homes made easy  im ...     1                1
3     Subject: 4 color printing special  request add...     1                1
4     Subject: do not have money , get software cds ...     1                1
...                                                 ...   ...              ...
5723  Subject: re : research and development charges...     0                0
5724  Subject: re : receipts from visit  jim ,  than...     0                0
5725  Subject: re : enron case study update  wow ! a...     0                0
5726  Subject: re : interest  david ,  please , call...     0                0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0                0

[5728 rows x 3 columns]

In [14]:

dummy = ["You won a car!!", "Free goodies, hurry up....dont miss the offer", "How are you, Good night!", "great discounts, just pay shipping!!"]

dummy_vec = vector.transform(dummy)
display (dummy_vec.shape)
display (dummy_vec.toarray())


(4, 37303)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:

display (classifier.predict(dummy_vec))


array([1, 1, 0, 1])